package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i route256/checkout/internal/domain.LOMSClient -o ./mocks/loms_client_minimock.go -n LOMSClientMock

import (
	"context"
	mm_domain "route256/checkout/internal/domain"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// LOMSClientMock implements domain.LOMSClient
type LOMSClientMock struct {
	t minimock.Tester

	funcCreateOrder          func(ctx context.Context, user int64, items []mm_domain.OrderItem) (o1 mm_domain.OrderID, err error)
	inspectFuncCreateOrder   func(ctx context.Context, user int64, items []mm_domain.OrderItem)
	afterCreateOrderCounter  uint64
	beforeCreateOrderCounter uint64
	CreateOrderMock          mLOMSClientMockCreateOrder

	funcStocks          func(ctx context.Context, sku uint32) (sa1 []mm_domain.Stock, err error)
	inspectFuncStocks   func(ctx context.Context, sku uint32)
	afterStocksCounter  uint64
	beforeStocksCounter uint64
	StocksMock          mLOMSClientMockStocks
}

// NewLOMSClientMock returns a mock for domain.LOMSClient
func NewLOMSClientMock(t minimock.Tester) *LOMSClientMock {
	m := &LOMSClientMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateOrderMock = mLOMSClientMockCreateOrder{mock: m}
	m.CreateOrderMock.callArgs = []*LOMSClientMockCreateOrderParams{}

	m.StocksMock = mLOMSClientMockStocks{mock: m}
	m.StocksMock.callArgs = []*LOMSClientMockStocksParams{}

	return m
}

type mLOMSClientMockCreateOrder struct {
	mock               *LOMSClientMock
	defaultExpectation *LOMSClientMockCreateOrderExpectation
	expectations       []*LOMSClientMockCreateOrderExpectation

	callArgs []*LOMSClientMockCreateOrderParams
	mutex    sync.RWMutex
}

// LOMSClientMockCreateOrderExpectation specifies expectation struct of the LOMSClient.CreateOrder
type LOMSClientMockCreateOrderExpectation struct {
	mock    *LOMSClientMock
	params  *LOMSClientMockCreateOrderParams
	results *LOMSClientMockCreateOrderResults
	Counter uint64
}

// LOMSClientMockCreateOrderParams contains parameters of the LOMSClient.CreateOrder
type LOMSClientMockCreateOrderParams struct {
	ctx   context.Context
	user  int64
	items []mm_domain.OrderItem
}

// LOMSClientMockCreateOrderResults contains results of the LOMSClient.CreateOrder
type LOMSClientMockCreateOrderResults struct {
	o1  mm_domain.OrderID
	err error
}

// Expect sets up expected params for LOMSClient.CreateOrder
func (mmCreateOrder *mLOMSClientMockCreateOrder) Expect(ctx context.Context, user int64, items []mm_domain.OrderItem) *mLOMSClientMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LOMSClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LOMSClientMockCreateOrderExpectation{}
	}

	mmCreateOrder.defaultExpectation.params = &LOMSClientMockCreateOrderParams{ctx, user, items}
	for _, e := range mmCreateOrder.expectations {
		if minimock.Equal(e.params, mmCreateOrder.defaultExpectation.params) {
			mmCreateOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateOrder.defaultExpectation.params)
		}
	}

	return mmCreateOrder
}

// Inspect accepts an inspector function that has same arguments as the LOMSClient.CreateOrder
func (mmCreateOrder *mLOMSClientMockCreateOrder) Inspect(f func(ctx context.Context, user int64, items []mm_domain.OrderItem)) *mLOMSClientMockCreateOrder {
	if mmCreateOrder.mock.inspectFuncCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("Inspect function is already set for LOMSClientMock.CreateOrder")
	}

	mmCreateOrder.mock.inspectFuncCreateOrder = f

	return mmCreateOrder
}

// Return sets up results that will be returned by LOMSClient.CreateOrder
func (mmCreateOrder *mLOMSClientMockCreateOrder) Return(o1 mm_domain.OrderID, err error) *LOMSClientMock {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LOMSClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LOMSClientMockCreateOrderExpectation{mock: mmCreateOrder.mock}
	}
	mmCreateOrder.defaultExpectation.results = &LOMSClientMockCreateOrderResults{o1, err}
	return mmCreateOrder.mock
}

// Set uses given function f to mock the LOMSClient.CreateOrder method
func (mmCreateOrder *mLOMSClientMockCreateOrder) Set(f func(ctx context.Context, user int64, items []mm_domain.OrderItem) (o1 mm_domain.OrderID, err error)) *LOMSClientMock {
	if mmCreateOrder.defaultExpectation != nil {
		mmCreateOrder.mock.t.Fatalf("Default expectation is already set for the LOMSClient.CreateOrder method")
	}

	if len(mmCreateOrder.expectations) > 0 {
		mmCreateOrder.mock.t.Fatalf("Some expectations are already set for the LOMSClient.CreateOrder method")
	}

	mmCreateOrder.mock.funcCreateOrder = f
	return mmCreateOrder.mock
}

// When sets expectation for the LOMSClient.CreateOrder which will trigger the result defined by the following
// Then helper
func (mmCreateOrder *mLOMSClientMockCreateOrder) When(ctx context.Context, user int64, items []mm_domain.OrderItem) *LOMSClientMockCreateOrderExpectation {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LOMSClientMock.CreateOrder mock is already set by Set")
	}

	expectation := &LOMSClientMockCreateOrderExpectation{
		mock:   mmCreateOrder.mock,
		params: &LOMSClientMockCreateOrderParams{ctx, user, items},
	}
	mmCreateOrder.expectations = append(mmCreateOrder.expectations, expectation)
	return expectation
}

// Then sets up LOMSClient.CreateOrder return parameters for the expectation previously defined by the When method
func (e *LOMSClientMockCreateOrderExpectation) Then(o1 mm_domain.OrderID, err error) *LOMSClientMock {
	e.results = &LOMSClientMockCreateOrderResults{o1, err}
	return e.mock
}

// CreateOrder implements domain.LOMSClient
func (mmCreateOrder *LOMSClientMock) CreateOrder(ctx context.Context, user int64, items []mm_domain.OrderItem) (o1 mm_domain.OrderID, err error) {
	mm_atomic.AddUint64(&mmCreateOrder.beforeCreateOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateOrder.afterCreateOrderCounter, 1)

	if mmCreateOrder.inspectFuncCreateOrder != nil {
		mmCreateOrder.inspectFuncCreateOrder(ctx, user, items)
	}

	mm_params := &LOMSClientMockCreateOrderParams{ctx, user, items}

	// Record call args
	mmCreateOrder.CreateOrderMock.mutex.Lock()
	mmCreateOrder.CreateOrderMock.callArgs = append(mmCreateOrder.CreateOrderMock.callArgs, mm_params)
	mmCreateOrder.CreateOrderMock.mutex.Unlock()

	for _, e := range mmCreateOrder.CreateOrderMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.o1, e.results.err
		}
	}

	if mmCreateOrder.CreateOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateOrder.CreateOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateOrder.CreateOrderMock.defaultExpectation.params
		mm_got := LOMSClientMockCreateOrderParams{ctx, user, items}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateOrder.t.Errorf("LOMSClientMock.CreateOrder got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateOrder.CreateOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateOrder.t.Fatal("No results are set for the LOMSClientMock.CreateOrder")
		}
		return (*mm_results).o1, (*mm_results).err
	}
	if mmCreateOrder.funcCreateOrder != nil {
		return mmCreateOrder.funcCreateOrder(ctx, user, items)
	}
	mmCreateOrder.t.Fatalf("Unexpected call to LOMSClientMock.CreateOrder. %v %v %v", ctx, user, items)
	return
}

// CreateOrderAfterCounter returns a count of finished LOMSClientMock.CreateOrder invocations
func (mmCreateOrder *LOMSClientMock) CreateOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.afterCreateOrderCounter)
}

// CreateOrderBeforeCounter returns a count of LOMSClientMock.CreateOrder invocations
func (mmCreateOrder *LOMSClientMock) CreateOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.beforeCreateOrderCounter)
}

// Calls returns a list of arguments used in each call to LOMSClientMock.CreateOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateOrder *mLOMSClientMockCreateOrder) Calls() []*LOMSClientMockCreateOrderParams {
	mmCreateOrder.mutex.RLock()

	argCopy := make([]*LOMSClientMockCreateOrderParams, len(mmCreateOrder.callArgs))
	copy(argCopy, mmCreateOrder.callArgs)

	mmCreateOrder.mutex.RUnlock()

	return argCopy
}

// MinimockCreateOrderDone returns true if the count of the CreateOrder invocations corresponds
// the number of defined expectations
func (m *LOMSClientMock) MinimockCreateOrderDone() bool {
	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateOrderMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateOrder != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		return false
	}
	return true
}

// MinimockCreateOrderInspect logs each unmet expectation
func (m *LOMSClientMock) MinimockCreateOrderInspect() {
	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LOMSClientMock.CreateOrder with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateOrderMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		if m.CreateOrderMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to LOMSClientMock.CreateOrder")
		} else {
			m.t.Errorf("Expected call to LOMSClientMock.CreateOrder with params: %#v", *m.CreateOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateOrder != nil && mm_atomic.LoadUint64(&m.afterCreateOrderCounter) < 1 {
		m.t.Error("Expected call to LOMSClientMock.CreateOrder")
	}
}

type mLOMSClientMockStocks struct {
	mock               *LOMSClientMock
	defaultExpectation *LOMSClientMockStocksExpectation
	expectations       []*LOMSClientMockStocksExpectation

	callArgs []*LOMSClientMockStocksParams
	mutex    sync.RWMutex
}

// LOMSClientMockStocksExpectation specifies expectation struct of the LOMSClient.Stocks
type LOMSClientMockStocksExpectation struct {
	mock    *LOMSClientMock
	params  *LOMSClientMockStocksParams
	results *LOMSClientMockStocksResults
	Counter uint64
}

// LOMSClientMockStocksParams contains parameters of the LOMSClient.Stocks
type LOMSClientMockStocksParams struct {
	ctx context.Context
	sku uint32
}

// LOMSClientMockStocksResults contains results of the LOMSClient.Stocks
type LOMSClientMockStocksResults struct {
	sa1 []mm_domain.Stock
	err error
}

// Expect sets up expected params for LOMSClient.Stocks
func (mmStocks *mLOMSClientMockStocks) Expect(ctx context.Context, sku uint32) *mLOMSClientMockStocks {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LOMSClientMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &LOMSClientMockStocksExpectation{}
	}

	mmStocks.defaultExpectation.params = &LOMSClientMockStocksParams{ctx, sku}
	for _, e := range mmStocks.expectations {
		if minimock.Equal(e.params, mmStocks.defaultExpectation.params) {
			mmStocks.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStocks.defaultExpectation.params)
		}
	}

	return mmStocks
}

// Inspect accepts an inspector function that has same arguments as the LOMSClient.Stocks
func (mmStocks *mLOMSClientMockStocks) Inspect(f func(ctx context.Context, sku uint32)) *mLOMSClientMockStocks {
	if mmStocks.mock.inspectFuncStocks != nil {
		mmStocks.mock.t.Fatalf("Inspect function is already set for LOMSClientMock.Stocks")
	}

	mmStocks.mock.inspectFuncStocks = f

	return mmStocks
}

// Return sets up results that will be returned by LOMSClient.Stocks
func (mmStocks *mLOMSClientMockStocks) Return(sa1 []mm_domain.Stock, err error) *LOMSClientMock {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LOMSClientMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &LOMSClientMockStocksExpectation{mock: mmStocks.mock}
	}
	mmStocks.defaultExpectation.results = &LOMSClientMockStocksResults{sa1, err}
	return mmStocks.mock
}

// Set uses given function f to mock the LOMSClient.Stocks method
func (mmStocks *mLOMSClientMockStocks) Set(f func(ctx context.Context, sku uint32) (sa1 []mm_domain.Stock, err error)) *LOMSClientMock {
	if mmStocks.defaultExpectation != nil {
		mmStocks.mock.t.Fatalf("Default expectation is already set for the LOMSClient.Stocks method")
	}

	if len(mmStocks.expectations) > 0 {
		mmStocks.mock.t.Fatalf("Some expectations are already set for the LOMSClient.Stocks method")
	}

	mmStocks.mock.funcStocks = f
	return mmStocks.mock
}

// When sets expectation for the LOMSClient.Stocks which will trigger the result defined by the following
// Then helper
func (mmStocks *mLOMSClientMockStocks) When(ctx context.Context, sku uint32) *LOMSClientMockStocksExpectation {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LOMSClientMock.Stocks mock is already set by Set")
	}

	expectation := &LOMSClientMockStocksExpectation{
		mock:   mmStocks.mock,
		params: &LOMSClientMockStocksParams{ctx, sku},
	}
	mmStocks.expectations = append(mmStocks.expectations, expectation)
	return expectation
}

// Then sets up LOMSClient.Stocks return parameters for the expectation previously defined by the When method
func (e *LOMSClientMockStocksExpectation) Then(sa1 []mm_domain.Stock, err error) *LOMSClientMock {
	e.results = &LOMSClientMockStocksResults{sa1, err}
	return e.mock
}

// Stocks implements domain.LOMSClient
func (mmStocks *LOMSClientMock) Stocks(ctx context.Context, sku uint32) (sa1 []mm_domain.Stock, err error) {
	mm_atomic.AddUint64(&mmStocks.beforeStocksCounter, 1)
	defer mm_atomic.AddUint64(&mmStocks.afterStocksCounter, 1)

	if mmStocks.inspectFuncStocks != nil {
		mmStocks.inspectFuncStocks(ctx, sku)
	}

	mm_params := &LOMSClientMockStocksParams{ctx, sku}

	// Record call args
	mmStocks.StocksMock.mutex.Lock()
	mmStocks.StocksMock.callArgs = append(mmStocks.StocksMock.callArgs, mm_params)
	mmStocks.StocksMock.mutex.Unlock()

	for _, e := range mmStocks.StocksMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sa1, e.results.err
		}
	}

	if mmStocks.StocksMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStocks.StocksMock.defaultExpectation.Counter, 1)
		mm_want := mmStocks.StocksMock.defaultExpectation.params
		mm_got := LOMSClientMockStocksParams{ctx, sku}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStocks.t.Errorf("LOMSClientMock.Stocks got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStocks.StocksMock.defaultExpectation.results
		if mm_results == nil {
			mmStocks.t.Fatal("No results are set for the LOMSClientMock.Stocks")
		}
		return (*mm_results).sa1, (*mm_results).err
	}
	if mmStocks.funcStocks != nil {
		return mmStocks.funcStocks(ctx, sku)
	}
	mmStocks.t.Fatalf("Unexpected call to LOMSClientMock.Stocks. %v %v", ctx, sku)
	return
}

// StocksAfterCounter returns a count of finished LOMSClientMock.Stocks invocations
func (mmStocks *LOMSClientMock) StocksAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocks.afterStocksCounter)
}

// StocksBeforeCounter returns a count of LOMSClientMock.Stocks invocations
func (mmStocks *LOMSClientMock) StocksBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocks.beforeStocksCounter)
}

// Calls returns a list of arguments used in each call to LOMSClientMock.Stocks.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStocks *mLOMSClientMockStocks) Calls() []*LOMSClientMockStocksParams {
	mmStocks.mutex.RLock()

	argCopy := make([]*LOMSClientMockStocksParams, len(mmStocks.callArgs))
	copy(argCopy, mmStocks.callArgs)

	mmStocks.mutex.RUnlock()

	return argCopy
}

// MinimockStocksDone returns true if the count of the Stocks invocations corresponds
// the number of defined expectations
func (m *LOMSClientMock) MinimockStocksDone() bool {
	for _, e := range m.StocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StocksMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStocks != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		return false
	}
	return true
}

// MinimockStocksInspect logs each unmet expectation
func (m *LOMSClientMock) MinimockStocksInspect() {
	for _, e := range m.StocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LOMSClientMock.Stocks with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.StocksMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		if m.StocksMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to LOMSClientMock.Stocks")
		} else {
			m.t.Errorf("Expected call to LOMSClientMock.Stocks with params: %#v", *m.StocksMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStocks != nil && mm_atomic.LoadUint64(&m.afterStocksCounter) < 1 {
		m.t.Error("Expected call to LOMSClientMock.Stocks")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LOMSClientMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockCreateOrderInspect()

		m.MinimockStocksInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LOMSClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LOMSClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateOrderDone() &&
		m.MinimockStocksDone()
}
